USE blog_db;
-- DROP TABLE blogs;
/* CREATE TABLE blogs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255),
    category VARCHAR(100) NOT NULL,
    cover_image VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    content LONGTEXT NOT NULL,
    tags VARCHAR(255) NOT NULL,
    views INT DEFAULT 0,
    likes INT DEFAULT 0,
    comments INT DEFAULT 0
); */

/* INSERT INTO blogs (id, title, subtitle, category, cover_image, created_at, content, tags, views, likes, comments) VALUES
(1, 'Mastering Python for Data Analysis', 'From Basics to Advanced Techniques', 'Data Analysis', 'https://example.com/images/python-data-analysis.jpg', '2023-10-01 12:00:00', 'Python has become the go-to language for data analysis due to its simplicity and powerful libraries like Pandas, NumPy, and Matplotlib. In this article, we’ll explore how to use Python for data cleaning, manipulation, and visualization. We’ll also dive into advanced techniques such as time series analysis and working with large datasets using Dask. Whether you’re a beginner or an experienced analyst, this guide will help you unlock the full potential of Python for data analysis.', 'python, data analysis, pandas, numpy, visualization', 1500, 120, 45),
(2, 'Introduction to Data Engineering with Python', 'Building Robust Data Pipelines', 'Data Engineering', 'https://example.com/images/data-engineering.jpg', '2023-09-25 09:30:00', 'Data engineering is the backbone of any data-driven organization. In this article, we’ll explore how Python can be used to build efficient and scalable data pipelines. We’ll cover tools like Apache Airflow for workflow orchestration, PySpark for big data processing, and SQLAlchemy for database interactions. You’ll also learn best practices for data validation, error handling, and monitoring. By the end of this guide, you’ll have a solid understanding of how to design and implement data pipelines using Python.', 'python, data engineering, airflow, pyspark, data pipelines', 2300, 300, 89),
(3, 'Machine Learning with Python: A Beginner''s Guide', 'From Theory to Practice', 'Machine Learning', 'https://example.com/images/ml-python.jpg', '2023-10-05 15:45:00', 'Machine learning is transforming industries, and Python is at the forefront of this revolution. In this guide, we’ll walk you through the basics of machine learning using Python’s Scikit-Learn library. We’ll cover key concepts like supervised and unsupervised learning, model evaluation, and hyperparameter tuning. You’ll also get hands-on experience by building a simple classification model. Whether you’re new to ML or looking to refresh your skills, this article will provide a strong foundation for your machine learning journey.', 'python, machine learning, scikit-learn, AI, data science', 1800, 250, 60),
(4, 'Deep Learning with TensorFlow and Python', 'Unlocking the Power of Neural Networks', 'Artificial Intelligence', 'https://example.com/images/tensorflow.jpg', '2023-09-30 11:20:00', 'Deep learning is a subset of machine learning that focuses on neural networks. In this article, we’ll explore how to use TensorFlow, one of the most popular deep learning frameworks, with Python. We’ll cover the basics of building and training neural networks, including convolutional neural networks (CNNs) for image recognition and recurrent neural networks (RNNs) for sequence data. You’ll also learn how to use TensorFlow’s high-level API, Keras, to simplify your workflow. By the end, you’ll have the tools to start building your own deep learning models.', 'python, deep learning, tensorflow, neural networks, AI', 1200, 90, 30),
(5, 'Data Visualization with Python', 'Turning Data into Insights', 'Data Analysis', 'https://example.com/images/data-visualization.jpg', '2023-10-10 08:00:00', 'Data visualization is a critical skill for any data professional. In this article, we’ll explore how to create stunning visualizations using Python libraries like Matplotlib, Seaborn, and Plotly. We’ll cover everything from basic charts to advanced interactive dashboards. You’ll also learn how to customize your visualizations to effectively communicate insights. Whether you’re presenting to stakeholders or exploring data for yourself, this guide will help you turn raw data into compelling stories.', 'python, data visualization, matplotlib, seaborn, plotly', 3000, 400, 120),
(6, 'Big Data Processing with PySpark', 'Scaling Data Analysis with Python', 'Data Engineering', 'https://example.com/images/pyspark.jpg', '2023-10-02 14:15:00', 'As datasets grow larger, traditional data processing tools often fall short. PySpark, the Python API for Apache Spark, is designed to handle big data with ease. In this article, we’ll explore how to use PySpark for distributed data processing. We’ll cover key concepts like RDDs, DataFrames, and Spark SQL. You’ll also learn how to optimize your PySpark jobs for performance. Whether you’re working with terabytes of data or just getting started with big data, this guide will help you harness the power of PySpark.', 'python, pyspark, big data, data engineering, apache spark', 2100, 180, 55),
(7, 'Natural Language Processing with Python', 'Understanding Text Data', 'Artificial Intelligence', 'https://example.com/images/nlp.jpg', '2023-09-28 10:10:00', 'Natural Language Processing (NLP) is a branch of AI that focuses on understanding and generating human language. In this article, we’ll explore how to use Python for NLP tasks like text classification, sentiment analysis, and named entity recognition. We’ll use libraries like NLTK, SpaCy, and Hugging Face Transformers. You’ll also learn how to preprocess text data and build your own NLP models. By the end, you’ll have the skills to tackle real-world NLP challenges using Python.', 'python, nlp, AI, text analysis, machine learning', 1700, 220, 70),
(8, 'Building Machine Learning Pipelines', 'From Data to Deployment', 'Machine Learning', 'https://example.com/images/ml-pipelines.jpg', '2023-10-07 16:30:00', 'Building a machine learning model is just one part of the process. In this article, we’ll explore how to create end-to-end machine learning pipelines using Python. We’ll cover data preprocessing, feature engineering, model training, and deployment using tools like Scikit-Learn, MLflow, and FastAPI. You’ll also learn how to monitor and maintain your models in production. Whether you’re a data scientist or an engineer, this guide will help you streamline your ML workflows.', 'python, machine learning, ml pipelines, scikit-learn, mlflow', 1400, 150, 40),
(9, 'AI in Healthcare: A Python Perspective', 'Transforming Medicine with Data', 'Artificial Intelligence', 'https://example.com/images/ai-healthcare.jpg', '2023-10-03 13:00:00', 'Artificial intelligence is revolutionizing healthcare, from diagnostics to personalized treatment plans. In this article, we’ll explore how Python is being used to build AI solutions in healthcare. We’ll cover topics like medical image analysis, predictive modeling, and natural language processing for electronic health records. You’ll also learn about the ethical considerations and challenges of deploying AI in healthcare. By the end, you’ll have a deeper understanding of how AI is transforming medicine and how you can contribute to this exciting field.', 'python, AI, healthcare, machine learning, data science', 2500, 280, 95),
(10, 'Automating Data Workflows with Python', 'Efficiency at Scale', 'Data Engineering', 'https://example.com/images/automation.jpg', '2023-10-08 17:00:00', 'Automation is key to handling repetitive data tasks efficiently. In this article, we’ll explore how to automate data workflows using Python. We’ll cover tools like Prefect for workflow orchestration, Pandas for data manipulation, and SQLAlchemy for database interactions. You’ll also learn how to schedule and monitor automated workflows using cron jobs and logging. Whether you’re a data engineer or analyst, this guide will help you save time and reduce errors by automating your data processes.', 'python, automation, data engineering, workflows, data pipelines', 3200, 500, 150); */